<!--
    Functions running in parallel with other
    functions are called asynchrounous
    A good example is JavaScript setTimeout()
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Asynchronous javascript</title>
</head>
<body>
    <script>
        const getTodos =(resource, callback)=>{
            return new Promise((resolve, reject)=>{
                const request = new XMLHttpRequest();
                request.addEventListener("readystatechange", ()=>{
                    //console.log(request);
                    //console.log(request.readyState);
                    if(request.readyState === 4 && request.status ===200){
                        const data = JSON.parse(request.responseText);
                        resolve(data);
                    }
                    else if(request.readyState === 4){
                        reject("error getting resource");
                    }
                });
                request.open("GET", resource);
                request.send();

            });
           
        };
        getTodos("todos/nilusche.json").then((data)=>{
            console.log("promise resolved", data)
        }).catch((error)=>{
            console.log("promise rejected", error);
        });
        //console.log(1);
        //console.log(2);
        //Callback hell
        /*
        getTodos('todos/nilusche.json',(error,data)=>{
            console.log(data);
            getTodos('todos/flexon.json', (error,data)=>{
                console.log(data);
                getTodos('todos/enni.json', (error, data)=>{
                    console.log(data);
                });
            });
        });*/

        const getSomething = ()=>{
            return new Promise((resolve, reject)=>{
                //fetch something
                resolve('some data');
                reject('some error');
            });
        };

        /*getSomething().then((data) => {
            console.log(data)
        }, (err) => {
            console.log(err)
        });*/
        getSomething().then((data)=>{
            console.log(data);
        }).catch((error)=>{
            console.log(error);
        })

        //console.log(3);
        //console.log(4);
        </script>
</body>
</html>